name = "OpticLobe"
uuid = "92dc4026-55ef-4800-9891-71f0edeabde7"
authors = ["Sebastian Seung <sseung@princeton.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
